# Generated by Django 5.2 on 2025-05-27 08:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webtechapp', '0003_tableexample'),
    ]

    operations = [
        migrations.DeleteModel(
            name='tableexample',
        ),
    ]
