# Generated by Django 5.2 on 2025-05-29 07:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webtechapp', '0005_student'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='username',
            new_name='name',
        ),
    ]
